### ISSUE TITLE
Sipi can't receive a chunked POST request, and crashes if Content-Length is too large

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#121]
If I send a file upload as chunked POST request to Sipi (e.g. to `/make_thumbnail`), Sipi doesn't process the upload. This is because it expects a `Content-Length` header, which is not part of a chunked request. A chunked request contains the header `Transfer-Encoding: chunked` instead. The HTTP 1.1 spec [says](https://tools.ietf.org/html/rfc2616#section-4.4):

> If a Content-Length header field (section 14.13) is present, its decimal value in OCTETs represents both the entity-length and the transfer-length. The Content-Length header field MUST NOT be sent if these two lengths are different (i.e., if a Transfer-Encoding header field is present). If a message is received with both a Transfer-Encoding header field and a Content-Length header field, the latter MUST be ignored.

To reproduce, start Sipi like this:

```
local/bin/sipi --config config/sipi.knora-config.lua
```

Then make a request like this:

```
curl -v -i -X POST -H "Content-Type: multipart/form-data" -H "Transfer-Encoding: chunked" --form "file=@test/_test_data/images/knora/Leaves.jpg" http://localhost:1024/make_thumbnail
```

The `make_thumbnail.lua` script returns an error saying `no image uploaded`.

The problem starts on line 474 of `Connection.cpp`:

```
                if (content_length > 0) {
```

Sipi checks whether the request is chunked only after checking the content length.

Also, the code there passes the value of the `Content-Length` header to `malloc`, without checking whether that's a reasonable value. This means that you can make Sipi crash by making a POST request with a very large content length (even without uploading a file):

```
curl -v -i -X POST -H "Content-Type: multipart/form-data" -H "Content-Length: 100000000000000" --form "file=@test/_test_data/images/knora/Leaves.jpg" http://localhost:1024/make_thumbnail
```

@lrosenth Would you consider replacing Sipi's HTTP server code with https://github.com/facebook/proxygen ?

**Comment by lrosenth** [comment]
Git it - will fix it!

Lukas

Sent from my iPad

On 7 Feb 2017, at 18:47, Benjamin Geer <notifications@github.com<mailto:notifications@github.com>> wrote:


If I send a file upload as chunked POST request to Sipi (e.g. to /make_thumbnail), Sipi doesn't process the upload. This is because it expects a Content-Length header, which is not part of a chunked request. A chunked request contains the header Transfer-Encoding: chunked instead. The HTTP 1.1 spec says<https://tools.ietf.org/html/rfc2616#section-4.4>:

If a Content-Length header field (section 14.13) is present, its decimal value in OCTETs represents both the entity-length and the transfer-length. The Content-Length header field MUST NOT be sent if these two lengths are different (i.e., if a Transfer-Encoding header field is present). If a message is received with both a Transfer-Encoding header field and a Content-Length header field, the latter MUST be ignored.

To reproduce:

curl -v -i -X POST -H "Content-Type: multipart/form-data" -H "Transfer-Encoding: chunked" --form "file=@test/_test_data/images/knora/Leaves.jpg" http://localhost:1024/make_thumbnail


The make_thumbnail.lua script returns an error saying no image uploaded.

The problem starts on line 474 of Connection.cpp:

                if (content_length > 0) {


Sipi checks whether the request is chunked only after checking the content length.

Also, the code there passes the value of the Content-Length header to malloc, without checking whether that's a reasonable value. This means that you can make Sipi crash by making a POST request with a very large content length (even without uploading a file):

curl -v -i -X POST -H "Content-Type: multipart/form-data" -H "Content-Length: 100000000000000" --form "file=@test/_test_data/images/knora/Leaves.jpg" http://localhost:1024/make_thumbnail


@lrosenth<https://github.com/lrosenth> Would you consider replacing the Sipi's HTTP server code with https://github.com/facebook/proxygen ?

**Comment by lrosenth** [comment]
OK, I think I'm almost got it. Will test and then add a parameter to the config file
