### ISSUE TITLE
Host needed libraries ourselves as Sourceforge is unreliable

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Sipi#142]
Please see: https://travis-ci.org/dhlab-basel/Sipi/jobs/212035499

**Comment by subotic** [comment]
I have added a `cron` job to Travis-CI, which will make sure that builds on `develop` run at least once every 24h so that these things can be caught on time.

**Comment by tobiasschweizer** [comment]
The sourceforge link is broken again because the updated the version?

**Comment by subotic** [comment]
Can't we put the `tar.gz` into our repository. This is a bit anoying, since it seems to brake in the worst moment.

**Comment by loicjaouen** [comment]
the problem was once fixed by downloading the latest version, instead of a given version ( #51 ).

It worked for a while, but sourceforge/libpng changed the default file format from `.gz` to `.xz` which broke `cmake` and we reverted to request a given version where we can ask the `.gz` zip format.

But @benjamingeer you added the `xz` support, didn't you?

**Comment by loicjaouen** [comment]
what I said before is wrong, `cmake` handles `xz` since quite some time ( [see ref](https://cmake.org/Bug/view.php?id=13515) ).  
This:
        URL https://sourceforge.net/projects/libpng/files/latest/download?source=files
        DOWNLOAD_NAME libpng-latest.tar.xz
works fine for the untar/unzip part but the build fails shortly after because the `latest` has a file that's not at the right place apparently (`pngusr.dfa` has moved from top directory to subdir `contrib/pngminim`).

I will have a second look tomorrow, but it looks like a path error in the script.

**Comment by benjamingeer** [comment]
@loicjaouen Sorry I forgot to reply to this. Thanks for investigating. SourceForge has been very unreliable in general. Some time ago we decided we should put all these libraries on our own server so the build process could download them from there, instead of from SourceForge. We just haven't found time to do it yet.

**Comment by loicjaouen** [comment]
ok, so for now I can just commit a line change for a version of png that works?

**Comment by benjamingeer** [comment]
Yes please!

**Comment by subotic** [comment]
just wondering, why do we need to put these libraries on our server? why not simply add them to the sipi repository?

**Comment by benjamingeer** [comment]
> Binaries bloat the repo cause they can't be diffed by git, so every time you update a binary, you increase size by that file's size - text files just store the diff. The repo gets larger and slower and on a checkout users also have to pull all those old binary files down, too.

https://github.com/openframeworks/openFrameworks/wiki/Moving-binaries-out-of-the-repo

**Comment by subotic** [comment]
What about https://git-lfs.github.com/ ? Will probably cost a bit, if the binaries are large. I have some concernes with the self-hosting solution regarding maintainance/reliability. We try already to do too much with the resources we have.

**Comment by benjamingeer** [comment]
Looks good but where would the files actually be stored? Would we have to pay for the hosting?

**Comment by subotic** [comment]
Maybe not such a good idea after all: https://medium.com/@megastep/github-s-large-file-storage-is-no-panacea-for-open-source-quite-the-opposite-12c0e16a9a91#.gcd73yb5d

**Comment by subotic** [comment]
We could open an S3 account and put these files on the Amazon Cloud. It costs only $0.0245 per GB per month. New accounts get 5GB per month free for the first year.

**Comment by benjamingeer** [comment]
Wow, LFS sounds awful. Yes, S3 seems fine to me!

**Comment by tobiasschweizer** [comment]
the link for limping is broken again on `develop`. 

https://sourceforge.net/projects/libpng/files/libpng16/older-releases/1.6.29/libpng-1.6.29.tar.gz/download works

**Comment by subotic** [comment]
Trying out [Bintray](https://bintray.com/dhlab-basel/thirdparty) for hosting our third-party libraries. It's a manual process, but faster than restarting Travis builds hundred times.

**Comment by subotic** [comment]
The solution with Bintray seems to work very well. I have moved all Sourceforge libraries to Bintray.
