### ISSUE TITLE
Segmentation fault: 11 when converting a JP2 file to TIFF (macOS Sierra)

### ISSUE THREAD

**Issue by mightymax** [dhlab-basel/Sipi#159]
When trying to convert a 50Mb JP2 file (lossless compression, created with Kakadu) Sipi fails due to a segmentation fault. The JP2 file kan be decompressed with Kakadu and results in a 207Mb TIFF file.

This is the command I've used:
`./bin/sipi --format tif  -f /tmp/in.jp2 /tmp/out.tif`
Trying to use the --size option gives the same issue:
`./bin/sipi --format tif --size 1024, -f /tmp/in.jp2 /tmp/out.tif`
Converting the image to JPEG works:
`./bin/sipi --format jpg  -f /tmp/in.jp2 /tmp/out.jpg`

**Comment by benjamingeer** [comment]
Thanks for reporting this, could you provide the JP2 file?

**Comment by mightymax** [comment]
Too big to upload, but please download it from my Dropbox: [https://www.dropbox.com/s/3vzytv2t2cccvxd/MMRKD08_COL_OZ15_450_20170115_0735.jp2?dl=0](url)

**Comment by lrosenth** [comment]
Ok, git the file and can reproduce the problem. In fact the tiff is being created, but SIpi fails in writing a specific exif tag. Will have a in depth look at the file.

Are You down at the posters?

Lukas
Am 17.05.2017 um 10:22 schrieb Mark Lindeman <notifications@github.com<mailto:notifications@github.com>>:


Too big to upload, but please download it from my Dropbox: https://www.dropbox.com/s/3vzytv2t2cccvxd/MMRKD08_COL_OZ15_450_20170115_0735.jp2?dl=0<x-msg://3/url>

**Comment by lrosenth** [comment]
OK, I fund thge bug… EXIFTAG_IMAGEUNIQUEID had a wrong datatype. Is fixed it and the pull-request on github is awaiting approval from one of my collegues in order to merge into the develop branch…

Lukas

Am 17.05.2017 um 10:22 schrieb Mark Lindeman <notifications@github.com<mailto:notifications@github.com>>:


Too big to upload, but please download it from my Dropbox: https://www.dropbox.com/s/3vzytv2t2cccvxd/MMRKD08_COL_OZ15_450_20170115_0735.jp2?dl=0<x-msg://6/url>

**Comment by mightymax** [comment]
Thanks Luke! Switched to your branch and I can confirm the problem is solved. Thanks for the quick service!
