### ISSUE TITLE
Error when importing tiffs

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Sipi#42]
After some images that were imported via route `convert_from_binaries`

```
terminate called after throwing an instance of 'Sipi::JpegError'
  what():  Application transferred too few scanlines
Aborted (core dumped)

```

**Comment by lrosenth** [comment]
plase test again with the openssl branch

**Comment by tobiasschweizer** [comment]
Sorry, this was my mistake and has nothing to do with SIPI. It just ran out of diskspace while writing files. The only thing that would be nice is an apt error message.

**Comment by lrosenth** [comment]
Giving a nice error message is not so easy because the writing is dine by the libjpeg functions...

Best Regards from Nice - at 14h the ferry leaves for corsica

Von meinem iPhone gesendet

Am 20.07.2016 um 08:27 schrieb Tobias Schweizer <notifications@github.com<mailto:notifications@github.com>>:


Sorry, this was my mistake and has nothing to do with SIPI. It just ran out of diskspace while writing files. The only thing that would be nice is an apt error message.
